base_config: hallway
scene_name: hallway_L_hex

blender_app: "/home/hieule/blender/blender-3.3.14-linux-x64/blender"
blender_dir: "/home/hieule/blender/"
xml_dir: "/home/hieule/research/saris_revised/local_assets/blender"
blender_script: "/home/hieule/research/saris_revised/rs/bscripts/generate_scene_focus_ma_2ue.py"
image_dir: "/home/hieule/research/saris_revised/local_assets/images"

resolution: [1920, 1080]
rm_vmin: -100
rm_vmax: -60
verbose: true
cam_position: [1.3, -4.0, 50.0]
cam_orientation: [0.0, 0.0, 0.0]
cam_look_at: [1.3, -4.0, 0.0]
frequency: 60e9
synthetic_array: true

# RIS parameters
rf_positions: [[11.2266, -5.75369, 1.93559], [11.0922, -5.88804, 2.06059]]

# Transmitter and receiver parameters
tx_power_dbm: 5.0
tx_num_rows: 1
tx_num_cols: 1
tx_vertical_spacing: 0.5
tx_horizontal_spacing: 0.5
tx_pattern: tr38901
tx_polarization: V
tx_positions: [[9.5, -1.5, 2.5], [9.5, -1.5, 2.5]]
tx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
rx_num_rows: 1
rx_num_cols: 1
rx_vertical_spacing: 0.5
rx_horizontal_spacing: 0.5
rx_pattern: iso
rx_polarization: V
rx_positions: [[-10.1, -2.75, 1.5], [-11.1, -3.25, 1.5]]
rx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

# Path tracing parameters
rm_max_depth: 7
rm_cell_size: [0.2, 0.2]
rm_num_samples: 1e6
# rm_stop_threshold: -90.0
rm_diffuse_reflection: true
rm_rr_depth: -1
path_max_depth: 8
path_num_samples: 1e6
