base_config: outdoor
scene_name: outdoor_small

blender_app: "/home/hieule/blender/blender-3.3.14-linux-x64/blender"
blender_dir: "/home/hieule/blender/"
xml_dir: "/home/hieule/research/saris_revised/local_assets/blender_outdoor"
blender_script: "/home/hieule/research/saris_revised/rs/bscripts/generate_outdoor_focus_ma_small.py"
image_dir: "/home/hieule/research/saris_revised/local_assets/images"

resolution: [1920, 1080]
rm_vmin: -100
rm_vmax: -60
verbose: true
cam_position: [0.0, -0.1, 500.0]
cam_orientation: [0.0, 0.0, 0.0]
cam_look_at: [0.0, 0.0, 0.0]
frequency: 59.99e9
synthetic_array: true

# RIS parameters
rf_positions:
    [
        [95.6559, 45.1403, 9.75429],
        [93.7897, 47.6764, 9.75429],
        [94.1579, 47.2265, 9.75429],
    ]

# Transmitter and receiver parameters
tx_power_dbm: 15.0
tx_num_rows: 1
tx_num_cols: 1
tx_vertical_spacing: 0.5
tx_horizontal_spacing: 0.5
tx_pattern: tr38901
tx_polarization: V
tx_positions: [[91.5, 23.3, 14.0], [91.5, 23.3, 14.0], [91.5, 23.3, 14.0]]
tx_orientations: [[0.0, 0.0, 0.0]]
rx_num_rows: 1
rx_num_cols: 1
rx_vertical_spacing: 0.5
rx_horizontal_spacing: 0.5
rx_pattern: iso
rx_polarization: V
rx_positions:
    [[43.9272, 9.46564, 1.5], [23.3456, 23.3671, 1.5], [-11.8509, -5.9425, 1.5]]
rx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
# rx_color: [0.4, 0.8, 0.4]
rx_color: [1, 1, 0]

# Path tracing parameters
rm_max_depth: 7
rm_cell_size: [3.0, 3.0]
rm_num_samples: 1e6
# rm_stop_threshold: -90.0
rm_diffuse_reflection: true
rm_rr_depth: -1
path_max_depth: 8
path_num_samples: 1e6

display_radius: 2.0
